services:
  laravel-app:
    container_name: laravel-app
    build: .
    volumes:
      - ./:/var/www/html
      #- ./laravel/storage:/var/www/html/laravel/storage # Mount storage with explicit binding
      #- ./public_html:/var/www/html/public_html # Map the public directory to the document root
    ports:
      - "9000:80"
    environment:
      # Set environment variables for the container
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:your-app-key
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE_USERS: users_db
      DB_DATABASE_GENERAL: general_db
      DB_DATABASE_SURVEY: survey_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: general_db # Default DB for initial setup
    ports:
      - "3307:3306"
    networks:
      - laravel-network

volumes:
  dbdata:

networks:
  laravel-network:
    driver: bridge
